### ISSUE TITLE
GitHub contribution chart shows lesser contributions in the portfolio website as compared to the actual chart in GitHub

### ISSUE THREAD

**Issue by adityamishra9** [Yash-pede/portfolio#23]
![image](https://github.com/user-attachments/assets/5acca808-6a9b-4b61-80de-23c0ef88af8c)
Actual image from [github](https://github.com/Yash-pede)

![image](https://github.com/user-attachments/assets/ca57d8be-16a6-438d-a969-19eb91b59f08)
Image of chart from Portfolio site

**Comment by Yash-pede** [comment]
**Great spot**

What could be possible fixes according to you 
Is it issue with the library or is it something else ?
