### ISSUE TITLE
Add SEO

### ISSUE THREAD

**Issue by Yash-pede** [Yash-pede/portfolio#25]
### Search Engine Optimization 

- [x] sitemaps 
- [x] roboto
- [x] social thumbnail 
- [x] improve html tags and metadata for Google recognition 
- [ ] add site to [Google console](https://search.google.com/search-console/about)

**Comment by adityamishra9** [comment]
please share DNS for adding site to Google Search Console

**Comment by Yash-pede** [comment]
> please share DNS for adding site to Google Search Console

DNS settings are to verify the website ownership 
It should be updated from where we have purchased the domain (Hostinger in our case ) It will be updated seprately
